v2: make some progress

diff --git a/v2/Makefile b/v2/Makefile
--- a/v2/Makefile
+++ b/v2/Makefile
@@ -30,10 +30,9 @@ editor:
 	go build -o /dev/null generator*.go
 
 generate:
-	echo -n > /tmp/ccgo.log
 	echo -n > log-generate
 	echo -n > log-generate-errors
-	go run generator*.go 2> log-generate-errors | tee log-generate
+	GO_GENERATE_DIR=/tmp/libc go run generator*.go 2> log-generate-errors | tee log-generate
 	cat log-generate-errors
 	go build -v ./...
 	# go install github.com/mdempsky/unconvert@latest
@@ -42,6 +41,7 @@ generate:
 	go test -v -count=1 ./... 2>&1 | tee -a log-generate
 	git status
 	grep 'TRC\|TODO\|ERRORF\|FAIL' log-generate || true
+	grep 'TRC\|TODO\|ERRORF\|FAIL' log-generate-errors || true
 
 dev:
 	echo -n > /tmp/ccgo.log
@@ -52,8 +52,9 @@ dev:
 	go build -v ./...  | tee -a log-generate
 	go test -v -count=1 ./... 2>&1 | tee -a log-generate
 	git status
-	grep 'TRC\|TODO\|ERRORF\|FAIL' /tmp/ccgo.log || true
 	grep 'TRC\|TODO\|ERRORF\|FAIL' log-generate || true
+	grep 'TRC\|TODO\|ERRORF\|FAIL' log-generate-errors || true
+	grep 'TRC\|TODO\|ERRORF\|FAIL' /tmp/ccgo.log || true
 
 test:
 	go test -v -timeout 24h 2>&1 | tee log-test
